name: Build (Windows Only)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  build:
    name: "Windows Build ${{ matrix.build_type }}"
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
      - if: ${{ matrix.platform == 'windows' }}
        name: sccache
        uses: hendrikmuhs/ccache-action@v1.2.9
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          variant: sccache
      - name: Configure and build
        shell: pwsh
        run: |
          cmake -B build -G "Ninja" `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DENABLE_GL_BACKEND=ON `
            -DENABLE_VK_BACKEND=ON `
            -DCMAKE_C_COMPILER_LAUNCHER=C:\\Users\\runneradmin\\.cargo\\bin\\sccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=C:\\Users\\runneradmin\\.cargo\\bin\\sccache

          cmake --build build --target game_gl --config ${{ matrix.build_type }} -j 1
          cmake --build build --target game_vk --config ${{ matrix.build_type }} -j 1
